/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calc.h"
#include <math.h>
//#include <stdio.h>

	int *
calc_addition_1_svc(CalcArgs *argp, struct svc_req *rqstp)
{
	static int  result;
//	printf("ADD %d %d", argp->a, argp->b);
	result = argp->a + argp->b;

	return &result;
}

	int *
calc_substraction_1_svc(CalcArgs *argp, struct svc_req *rqstp)
{
	static int  result;
//	printf("SUB %d %d", argp->a, argp->b);
	result = argp->a - argp->b;

	return &result;
}

	int *
calc_mulitiplication_1_svc(CalcArgs *argp, struct svc_req *rqstp)
{
	static int  result;
//	printf("MUL %d %d", argp->a, argp->b);
	result = argp->a * argp->b;

	return &result;
}

	int *
calc_division_1_svc(CalcArgs *argp, struct svc_req *rqstp)
{
	static int  result;
//	printf("DIV %d %d", argp->a, argp->b);
	if (argp->b == 0)
		result = -1;
	else 
		result = argp->a / argp->b;


	return &result;
}

	int *
calc_power_1_svc(CalcArgs *argp, struct svc_req *rqstp)
{
	static int  result;
//	printf("POWER %d %d", argp->a, argp->b);
	result =argp->a;
	int i;
	for(i=1; i<argp->b; i++) {
		result *= argp->a;
	}
	//	result = (int)pow(argp->a, argp->b);

	return &result;
}
