/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calc.h"
#include <string.h>
#include <stdlib.h>

enum precedence {
	add = 0,
	substract,
	multiply,
	divide,
	power
};

#define MAX_INPUT_LEN 200
#define NUM_ERROR -999

int get_precedence(char*op) {
	if (!strcmp(op,"**")) {
		return power;
	} else if (!strcmp(op, "*")) {
		return multiply;
	} else if( !strcmp(op, "/")) {
		return divide;
	} else if (!strcmp(op, "+")) {
		return add;
	} else if (!strcmp(op,"-")) {
		return substract;
	}
	return NUM_ERROR;
}

int stack_num[100], stack_op[50];
int num_top=-1, op_top=-1;

void push_num(int num) {
	stack_num[++num_top] = num;
}
void push_op(int op) {
	stack_op[++op_top] = op;
}

int pop_num() {
	if(num_top < 0)	return NUM_ERROR;
	return stack_num[num_top--];
}

int pop_op() {
	if(op_top < 0) return NUM_ERROR;
	return stack_op[op_top--];
}

CLIENT *clnt;

int calc(int left, int right, int op)
{
	int *result;
	CalcArgs  calcArgs;
	calcArgs.a = left;
	calcArgs.b = right;
	switch (op) {
		case add:
			result = calc_addition_1(&calcArgs, clnt);
			if (result == (int *) NULL) {
				clnt_perror (clnt, "call failed");
			}
			break;
		case substract:
			result = calc_substraction_1(&calcArgs, clnt);
			if (result == (int *) NULL) {
				clnt_perror (clnt, "call failed");
			}
			break;
		case multiply:
			result = calc_mulitiplication_1(&calcArgs, clnt);
			if (result == (int *) NULL) {
				clnt_perror (clnt, "call failed");
			}
			break;
		case divide:
			result = calc_division_1(&calcArgs, clnt);
			if (result == (int *) NULL) {
				clnt_perror (clnt, "call failed");
			}
			if (*result == -1)
				return NUM_ERROR;
			break;
		case power:
			result = calc_power_1(&calcArgs, clnt);
			if (result == (int *) NULL) {
				clnt_perror (clnt, "call failed");
			}
			break;
	}
	return *result;
}

int calculate_and_push()
{
	int op_tmp, right, left, result;

	op_tmp = pop_op();
	right = pop_num();
	left = pop_num();
	if (op_tmp==NUM_ERROR || right == NUM_ERROR || left == NUM_ERROR)	return NUM_ERROR; /* error */

	result = calc(left,right,op_tmp);			
	if(result == NUM_ERROR)	return NUM_ERROR; /* error */

	push_num(result);
	return 0;			
}

int main (int argc, char *argv[])
{
	char *host;
	char *input;
	int debug = 0;
	int i,j, value;
	int left,right;
	int op_tmp;
	char cbuf[10], op[3];

	input = (char*) malloc(MAX_INPUT_LEN);	

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];

	// Intialize RPC
	clnt = clnt_create (host, CALC_PROG, CALC_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}

command:
	printf("type 'test' or 'exit'\n");
	fgets(input, MAX_INPUT_LEN, stdin);
	input = strtok(input, "\n");
	if(!strcmp(input, "test"))
		goto calc;
	else if(!strcmp(input, "exit"))
		goto exit;
	else
		goto command;

calc:
	printf("expression > ");
	fgets(input, MAX_INPUT_LEN, stdin);
	input = strtok(input, "\n");

	for (i=0; i<strlen(input); i++) {
		if (debug) printf("start i : %d\n", i);

		if ( '0' <= input[i] && input[i] <= '9') { /* number */
			for(j=i; j<strlen(input) && '0' <= input[j] && input[j] <= '9'; j++);

			strncpy(cbuf,input+i, j-i);
			cbuf[j-i]='\0';
			value = atoi(cbuf);
			if (debug) printf("number : %d\n", value);

			push_num(value);	

		} else { /* operator */
			for(j=i; j<strlen(input) && !('0' <= input[j] && input[j] <= '9'); j++);

			strncpy(op, input+i, j-i);
			op[j-i] = '\0';
			if (debug) printf("operator : %s\n", op);
			value = get_precedence(op);
			if (value == NUM_ERROR){
				printf("error occured while calculation\n");
				goto command;
			}

			while(op_top>=0 && stack_op[op_top]/2 > value/2) {
				if(calculate_and_push()) { /* error */
					printf("error occured while calculation\n");
					goto command;
				}
			}

			push_op(value);
		}
		i=j-1;
		if (debug) printf("i : %d, j : %d\n", i, j);
	}

	while(op_top>=0) {
		if(calculate_and_push()) { /* error */
			printf("error occured while calculation\n");
			goto command;
		}
	}

	printf("The answer is %d\n", pop_num());
	goto command;

exit:
	clnt_destroy (clnt);

	exit (0);
}
